plugins:
  - rubocop-rake
  - rubocop-rspec

RSpec/MultipleExpectations:
  Max: 5 # 1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
